using UnityEngine;
using UnityEngine.Serialization;

[CreateAssetMenu(fileName = "EncyclopediaEntry", menuName = "AlbuRIOT/Encyclopedia/Entry")]
public class EncyclopediaEntry : ScriptableObject
{
    [Header("Enemy Identification")]
    [Tooltip("Select enemy type from dropdown. enemyId is auto-synced from enemy data when available.")]
    public EnemyType enemyType = EnemyType.Aswang;
    [Tooltip("Unique ID used internally (auto-managed from enemy type).")]
    public string enemyId;
    
    [Header("Display Info")]
    [Tooltip("When enabled, description and lore are generated from enemy type and moveset/power profile.")]
    public bool autoGenerateDisplayText = true;
    public string displayName;
    [TextArea(3, 10)]
    public string description;
    [TextArea(2, 5)]
    public string firstEncounterText; // Shown when first encountering the enemy
    
    [Header("Visual")]
    public Sprite icon;
    public Sprite fullImage; // Optional larger image for encyclopedia view
    
    [Header("Stats (for display)")]
    public int baseHealth;
    public int baseDamage;
    public float moveSpeed;
    
    [Header("Power Stealing Text")]
    [FormerlySerializedAs("loreText")]
    [TextArea(2, 5)]
    public string powerStealingText;
    
    [Header("Unlock Condition")]
    [Tooltip("If true, entry is unlocked on first encounter. If false, requires kill.")]
    public bool unlockOnEncounter = false;

    public bool MatchesEnemyId(string candidateId)
    {
        if (string.IsNullOrWhiteSpace(candidateId)) return false;

        // exact ID match is preferred
        if (!string.IsNullOrWhiteSpace(enemyId) && string.Equals(enemyId, candidateId, System.StringComparison.OrdinalIgnoreCase))
            return true;

        // fallback to matching selected enemy type string
        if (string.Equals(enemyType.ToString(), candidateId, System.StringComparison.OrdinalIgnoreCase))
            return true;

        string normalizedCandidate = NormalizeId(candidateId);
        if (string.IsNullOrEmpty(normalizedCandidate)) return false;

        string normalizedEnemyId = NormalizeId(enemyId);
        if (!string.IsNullOrEmpty(normalizedEnemyId) && normalizedEnemyId == normalizedCandidate)
            return true;

        string normalizedEnemyType = NormalizeId(enemyType.ToString());
        return !string.IsNullOrEmpty(normalizedEnemyType) && normalizedEnemyType == normalizedCandidate;
    }

    private static string NormalizeId(string value)
    {
        if (string.IsNullOrWhiteSpace(value)) return string.Empty;

        value = value.Trim().ToLowerInvariant();
        value = value.Replace(" ", string.Empty);
        value = value.Replace("_", string.Empty);
        value = value.Replace("-", string.Empty);
        return value;
    }

    private static string ToDisplayName(EnemyType type)
    {
        string raw = type.ToString();
        if (string.IsNullOrEmpty(raw)) return "Unknown";

        var chars = new System.Text.StringBuilder(raw.Length + 8);
        chars.Append(raw[0]);
        for (int i = 1; i < raw.Length; i++)
        {
            if (char.IsUpper(raw[i]) && !char.IsUpper(raw[i - 1]))
                chars.Append(' ');
            chars.Append(raw[i]);
        }
        return chars.ToString();
    }

    private void OnValidate()
    {
        EnemyData data = EnemyFactory.GetEnemyData(enemyType);

        // always keep enemyId deterministic from selected type/data
        if (data != null && !string.IsNullOrWhiteSpace(data.enemyName))
            enemyId = data.enemyName.Trim();
        else
            enemyId = enemyType.ToString();

        // use enemy data as baseline display values
        if (data != null)
        {
            if (autoGenerateDisplayText)
                displayName = !string.IsNullOrWhiteSpace(data.enemyName) ? data.enemyName.Trim() : ToDisplayName(enemyType);
            else if (string.IsNullOrWhiteSpace(displayName))
                displayName = !string.IsNullOrWhiteSpace(data.enemyName) ? data.enemyName.Trim() : ToDisplayName(enemyType);

            baseHealth = data.maxHealth;
            baseDamage = data.basicDamage;
            moveSpeed = data.moveSpeed;
        }
        else
        {
            if (autoGenerateDisplayText)
                displayName = ToDisplayName(enemyType);
            else if (string.IsNullOrWhiteSpace(displayName))
                displayName = ToDisplayName(enemyType);
        }

        if (autoGenerateDisplayText)
        {
            GenerateDisplayText();
        }
    }

    private void GenerateDisplayText()
    {
        description = GetLoreParagraphDescription();
        powerStealingText = GetPowerStealingText();
    }

    private string GetLoreParagraphDescription()
    {
        switch (enemyType)
        {
            case EnemyType.Aswang:
                return "Among the most feared figures in Philippine folklore, the aswang is commonly described not as a single being but as a category of predatory shapeshifters associated with night hunting, secrecy, and deception. Regional traditions present many forms and habits, yet most accounts agree on its unnatural hunger and ability to hide behind ordinary appearances. In cultural memory, the aswang often represents social fear of the unseen danger within familiar communities.";
            case EnemyType.Manananggal:
                return "Traditionally identified as a distinct aswang type, the manananggal is known for separating its upper torso and taking flight after dark. Folkloric accounts often depict it as a nocturnal predator linked to rooftops, windows, and vulnerable households. Its legend carries themes of dual identity, where outward human form conceals a violent nature that emerges in darkness.";
            case EnemyType.Tikbalang:
                return "Characterized in many stories as horse-headed and human-bodied, the tikbalang is a trickster spirit associated with misdirection and confusion. Oral traditions often explain lost paths, circular journeys, and sudden disorientation through tikbalang influence. Rather than brute predation alone, it is remembered for manipulating perception and turning certainty into doubt.";
            case EnemyType.Kapre:
                return "Typically described as a towering giant dwelling in old trees, the kapre is tied to deep forests and enduring natural spaces. Folk narratives portray it as territorial yet not always malicious, with behavior shaped by respect, provocation, and boundary crossing. As a mythic figure, the kapre frequently symbolizes ancient presence and the warning that sacred landscapes are never truly empty.";
            case EnemyType.Tiyanak:
                return "In numerous Philippine tales, the tiyanak appears in infant-like form to exploit compassion before revealing a predatory nature. Accounts differ by region, but many emphasize sudden shifts from helplessness to violence. The figure is often interpreted as a cautionary symbol about deceptive appearances, misplaced trust, and the vulnerability of those who ignore warning signs.";
            case EnemyType.Bakunawa:
                return "Bakunawa is a colossal serpent-like being in Visayan mythology, most widely remembered for devouring moons and causing eclipses. Its imagery connects oceanic depth, celestial disruption, and cosmic imbalance in a single mythic form. Beyond creature lore, Bakunawa occupies an explanatory role in traditional storytelling, linking astronomical events to spiritual and moral order.";
            case EnemyType.Minokawa:
                return "Minokawa is described in Mindanao lore as an immense sky creature associated with consuming light and unsettling the balance of day and night. The figure carries apocalyptic undertones, often representing cosmic-scale threat rather than local haunting. In mythic interpretation, Minokawa embodies fear of celestial disorder and the fragility of natural cycles.";
            case EnemyType.Berberoka:
                return "Found in water-centered folklore, berberoka is often portrayed as an ambush predator that uses marshes, rivers, and sudden floods to entrap victims. Narrative emphasis is placed on cunning behavior rather than open confrontation. Culturally, the legend serves as a warning about deceptive calm in wetland environments and the hidden danger beneath still water.";
            case EnemyType.Sigbin:
                return "The sigbin appears in local superstition as a cryptic night creature linked to stealth, abrupt movement, and unsettling silence. Descriptions vary significantly across communities, but many accounts stress fleeting sightings and difficulty of pursuit. Its folklore presence reflects anxiety around the barely seen threat that vanishes before it can be fully understood.";
            case EnemyType.Sirena:
                return "Within coastal and island traditions, the sirena is a merfolk spirit associated with beauty, song, and perilous enchantment. Many stories frame encounters with sirena as moments where wonder and danger coexist, especially in deep or unpredictable waters. The figure reflects long-standing maritime themes of attraction, loss, and respect for forces beyond human control.";
            case EnemyType.Wakwak:
                return "The wakwak is frequently portrayed as a nocturnal aerial predator announced by ominous sounds before visual contact. Folklore surrounding it emphasizes dread, anticipation, and the fear of attack from above. As a narrative motif, wakwak stories often transform ordinary nighttime soundscapes into signs of imminent danger.";
            case EnemyType.Pugot:
                return "In many ghost-lore accounts, the pugot is depicted as a headless or faceless wandering entity associated with taboo spaces and boundary transgression. The image evokes punishment, moral consequence, and dread linked to places considered spiritually charged. Its enduring role in folklore is to mark thresholds where ordinary rules no longer apply.";
            case EnemyType.Sarimanok:
                return "Revered in Maranao and wider Mindanao artistic tradition, the sarimanok is a legendary bird symbol associated with royalty, fortune, and spiritual prestige. Unlike purely monstrous figures, it functions as a cultural emblem carrying ceremonial and visual significance. Its representation highlights the breadth of Philippine mythic tradition beyond horror-centered archetypes.";
            case EnemyType.BadDiwataPunso:
                return "Bad Diwata Punso represents a corrupted guardian-spirit archetype connected to desecrated mounds and broken ritual reciprocity. Folklore around diwata and punso commonly stresses respectful coexistence with sacred sites and unseen inhabitants. This form reflects the reversal of that covenant, where neglect or intrusion transforms guardianship into hostility.";
            case EnemyType.ShadowTouchedDiwata:
                return "The Shadow-Touched Diwata is presented as a fallen guardian spirit transformed by corruption rather than born from innate malice. In mythic terms, it reflects a recurring principle: spiritual beings mirror the moral and ecological condition of their surroundings. Its lore emphasizes decline, contamination, and the tragic inversion of protective power.";
            case EnemyType.Bungisngis:
                return "Bungisngis is a one-eyed giant in Philippine folktales, recognizable by extraordinary strength and a laugh that is unsettling rather than joyful. Narrative focus tends toward direct physical threat, distinguishing it from trickster-oriented spirits. The creature is often used to personify brute force unchecked by wisdom or restraint.";
            case EnemyType.Busaw:
                return "Busaw is commonly described as a ghoul-like predatory spirit associated with carrion, burial grounds, and taboo appetite. Regional variants differ in detail but frequently emphasize decay, desecration, and relentless feeding behavior. In folklore function, busaw narratives warn against spaces where death is disturbed or left without proper rites.";
            case EnemyType.AswangQueen:
                return "The Aswang Queen is a sovereign-form interpretation of aswang mythology, emphasizing hierarchy, dominion, and deliberate predation. As a figure, she transforms scattered fear into organized threat, suggesting command over lesser creatures. This archetype extends the aswang tradition from solitary horror toward structured mythic rulership.";
            case EnemyType.Amomongo:
                return "Amomongo is often described as an ape-like wild terror in modern local legend, linked to mountain fear and violent ambush behavior. Its identity sits between beast and spirit, producing descriptions that feel both zoological and uncanny. Folkloric treatment emphasizes primal aggression and sudden eruptions of force in isolated terrain.";
            default:
                return $"{displayName} is recorded in Philippine-inspired mythic taxonomy as an entity shaped by regional belief, spiritual symbolism, and inherited oral tradition. Its profile combines environmental association, behavioral pattern, and cultural meaning rather than simple monstrous identity. As with many folklore beings, interpretation varies by locality while core thematic traits remain recognizable.";
        }
    }

    private string GetPowerStealingText()
    {
        PowerStealData profile = FindPowerProfile();
        string moveName = ResolveMoveName(profile);
        string moveFlavor = ResolveMoveFlavor(profile);
        string powerName = ResolvePowerName(profile, moveName);

        return $"power stolen: {powerName}. source pattern: {moveName}. {moveFlavor}";
    }

    private string ResolvePowerName(PowerStealData profile, string fallbackMoveName)
    {
        if (profile != null && !string.IsNullOrWhiteSpace(profile.powerName))
            return profile.powerName.Trim();

        return fallbackMoveName;
    }

    private PowerStealData FindPowerProfile()
    {
        var dtm = DataTableManager.Instance;
        if (dtm == null)
            return null;

        if (!string.IsNullOrWhiteSpace(enemyId))
        {
            var byId = dtm.GetPowerStealData(enemyId.Trim());
            if (byId != null) return byId;
        }

        var byType = dtm.GetPowerStealData(enemyType.ToString());
        if (byType != null) return byType;

        if (!string.IsNullOrWhiteSpace(displayName))
        {
            var byName = dtm.GetPowerStealData(displayName.Trim());
            if (byName != null) return byName;
        }

        return null;
    }

    private string ResolveMoveName(PowerStealData profile)
    {
        if (profile != null)
        {
            if (profile.movesetData != null && !string.IsNullOrWhiteSpace(profile.movesetData.movesetName))
                return profile.movesetData.movesetName;

            if (!string.IsNullOrWhiteSpace(profile.powerName))
                return profile.powerName;
        }

        switch (enemyType)
        {
            case EnemyType.Aswang: return "Aswang Leap";
            case EnemyType.Manananggal: return "Manananggal Dive";
            case EnemyType.Tiyanak: return "Tiyanak Leap";
            case EnemyType.Sigbin: return "Shadow Veil";
            case EnemyType.Berberoka: return "Berberoka Vortex";
            case EnemyType.Bungisngis: return "Bungisngis Shout";
            case EnemyType.Tikbalang: return "Tikbalang Stomp";
            case EnemyType.Kapre: return "Kapre Strength";
            case EnemyType.Amomongo: return "Primal Surge";
            case EnemyType.Bakunawa: return "Tidal Pull";
            case EnemyType.Minokawa: return "Solar Wrath";
            default:
                return $"{displayName} Assault Pattern";
        }
    }

    private string ResolveMoveFlavor(PowerStealData profile)
    {
        if (profile != null)
        {
            switch (profile.powerType)
            {
                case PowerStealData.PowerType.Mobility:
                    return "It is known for sudden bursts and distance-closing movement that shifts the tempo of a hunt.";
                case PowerStealData.PowerType.Control:
                    return "Its move pattern bends battlefield flow, often forcing clustered targets into disarray.";
                case PowerStealData.PowerType.Stealth:
                    return "Witness accounts describe it as brief, elusive, and difficult to track between strikes.";
                case PowerStealData.PowerType.Buff:
                    return "During active phases, it enters heightened states that amplify presence and pressure.";
                case PowerStealData.PowerType.Attack:
                    return "Its sequence centers on direct impact and short windows of violent commitment.";
                default:
                    return "The movement cadence suggests a predatory rhythm built around brief commits and resets.";
            }
        }

        switch (enemyType)
        {
            case EnemyType.Manananggal:
            case EnemyType.Wakwak:
                return "Old notes repeatedly mention aerial pressure and abrupt descents in its combat rhythm.";
            case EnemyType.Berberoka:
            case EnemyType.Sirena:
                return "Its actions are often tied to water-space control and momentum shifts near flood paths.";
            case EnemyType.Kapre:
            case EnemyType.Bungisngis:
            case EnemyType.Busaw:
                return "Field records frame it as a heavy-force aggressor with overpowering close-range sequences.";
            default:
                return "Chronicles describe a measured but dangerous sequence of pressure, commit, and withdrawal.";
        }
    }
}

